<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Phanes.Task-5e744a86-c783-4ae0-aa18-c2ad7658da11</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.13.2" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Serilog.Formatting.Compact" Version="3.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="StackExchange.Redis" Version="2.12.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Phanes.Task.Contracts\Phanes.Task.Contracts.csproj" />
    <ProjectReference Include="..\Phanes.Task.Common\Phanes.Task.Common.csproj" />
  </ItemGroup>
</Project>
